# Generated by Django 2.0 on 2017-12-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VIOinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instancename', models.CharField(max_length=100)),
                ('imagename', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('availabilityzone', models.CharField(max_length=100)),
                ('powerstate', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-instancename',),
            },
        ),
    ]
