# Generated by Django 2.0 on 2017-12-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evrytesttools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuerySRRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=100)),
                ('classification_description', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('configuration_item_name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('disksize', models.CharField(max_length=100)),
                ('memsize', models.CharField(max_length=100)),
                ('virtualsize', models.CharField(max_length=100)),
                ('cpusize', models.CharField(max_length=100)),
                ('hypervisor', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-sr',),
            },
        ),
    ]
