# Generated by Django 2.0 on 2017-12-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evrytesttools', '0003_auto_20171207_0300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuerySRRecords',
            new_name='QuerySRRecord',
        ),
    ]
