# Generated by Django 2.0 on 2017-12-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evrytesttools', '0006_srcreateserverlinuxrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srcreateserverlinuxrecord',
            name='disasterlevelclass',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
