# Generated by Django 2.0 on 2017-12-11 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evrytesttools', '0007_auto_20171212_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srcreateserverlinuxrecord',
            name='disasterlevelclass',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
