# Generated by Django 2.0 on 2017-12-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evrytesttools', '0008_auto_20171212_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='srcreateserverlinuxrecord',
            name='operationusername',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
