# Generated by Django 2.0 on 2017-12-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evrytesttools', '0009_srcreateserverlinuxrecord_operationusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIORecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('instancename', models.CharField(max_length=100)),
                ('imagename', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('availabilityzone', models.CharField(max_length=100)),
                ('powerstate', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-instancename', '-date'),
            },
        ),
        migrations.DeleteModel(
            name='VIOinfo',
        ),
    ]
