# Generated by Django 2.0 on 2017-12-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evrytesttools', '0010_auto_20171219_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinuxInfoRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('hypervisortogetpassword', models.CharField(max_length=100)),
                ('customertogetpassword', models.CharField(max_length=100)),
                ('instancehostnametogetpassword', models.CharField(max_length=100)),
                ('instanceiptogetpassword', models.CharField(max_length=100)),
                ('Hostname', models.CharField(max_length=100)),
                ('IP', models.CharField(max_length=100)),
                ('CPUnumber', models.CharField(max_length=100)),
                ('MEM', models.CharField(max_length=100)),
                ('Disk', models.CharField(max_length=100)),
                ('NTPTimeZone', models.CharField(max_length=100)),
                ('DNSstatus', models.CharField(max_length=100)),
                ('ITMINFO', models.CharField(max_length=100)),
                ('BigfixINFO', models.CharField(max_length=100)),
                ('InstancePassword', models.CharField(max_length=100)),
                ('logfilepath', models.CharField(max_length=100)),
                ('detailogs', models.TextField(max_length=5000)),
            ],
            options={
                'ordering': ('-Hostname', '-date'),
            },
        ),
    ]
