# Generated by Django 2.0 on 2017-12-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evrytesttools', '0011_linuxinforecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='RundeckRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('srid', models.CharField(max_length=100)),
                ('icdDispatcherJobID', models.CharField(max_length=100)),
                ('icdDispatcherJobStatus', models.CharField(max_length=100)),
                ('icdDispatcherJobDuration', models.CharField(max_length=100)),
                ('workorderid', models.CharField(max_length=100)),
                ('privatecloudJobID', models.CharField(max_length=100)),
                ('privatecloudJobStatus', models.CharField(max_length=100)),
                ('privatecloudJobDuration', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-srid', '-date'),
            },
        ),
    ]
