# Generated by Django 2.0 on 2018-01-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evrytesttools', '0013_rundeckrecord_privatecloudjobtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndtoendRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('srid', models.CharField(max_length=100)),
                ('endtoendID', models.CharField(max_length=100)),
                ('createSRID', models.CharField(max_length=100)),
                ('querySRID', models.CharField(max_length=100)),
                ('cmdbID', models.CharField(max_length=100)),
                ('vioID', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('endtoendID', '-srid', '-date'),
            },
        ),
    ]
