# Generated by Django 2.0 on 2018-01-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evrytesttools', '0014_endtoendrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endtoendrecord',
            options={'ordering': ('endtoendID', '-date')},
        ),
        migrations.RemoveField(
            model_name='endtoendrecord',
            name='srid',
        ),
    ]
