# Generated by Django 2.0 on 2018-01-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evrytesttools', '0016_endtoendrecord_linuxinstanceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='endtoendrecord',
            name='rundeckID',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
